# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZAPInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('user', models.CharField(max_length=255, verbose_name='Username')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='End Time')),
            ],
        ),
        migrations.CreateModel(
            name='ZAPServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='Registration Time')),
                ('unregister_time', models.DateTimeField(auto_now=True, verbose_name='De-registration Time')),
            ],
        ),
        migrations.AddField(
            model_name='zapinstance',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ZAPServer', verbose_name='Server'),
        ),
    ]
