# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170215_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapinstance',
            name='pid',
            field=models.IntegerField(default=1234, verbose_name='PID'),
            preserve_default=False,
        ),
    ]
